### ISSUE TITLE
Not compatible with Unit 1.4

### ISSUE THREAD

**Issue by Tab10id** [murakmii/capistrano-nginx-unit#1]
In 1.4 changed path for config object https://unit.nginx.org/CHANGES.txt
Now it '/config' instead of '/'.
We fixed it in 73548e7c2fbee2dbd44c27b99a02f35567c2cc34
But it broke backward compatibility with 1.3 and below.
If you want to save backward compatibility we need to check version of unit.
Version of unit can be parsed from http headers.
What do you think?

**Comment by murakmii** [comment]
@Tab10id 
Thank you for your issue!
Sorry, I missed the change...

I built and checked the behavior of Unit 1.2, Unit 1.3 and Unit 1.4.
The result is following.

#### PUT to "/" on Unit 1.2

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost
```

```
{
	"success": "Reconfiguration done."
}
```

#### PUT to "/config" on Unit 1.2

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost/config
```

```
{
	"success": "Reconfiguration done."
}
```

#### PUT to "/" on Unit 1.3

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost
```

```
{
	"success": "Reconfiguration done."
}
```

#### PUT to "/config" on Unit 1.3

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost/config
```

```
{
	"success": "Reconfiguration done."
}
```

#### PUT to "/" on Unit 1.4

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost
```

```
{
	"error": "Invalid method."
}
```

#### PUT to "/config" on Unit 1.4

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost/config
```

```
{
	"success": "Reconfiguration done."
}
```

OK, Unit that below version 1.3 supports both request path `"/"` and `"/config"`.
Therefore, I think your fix still keep backward compatibility.

I will refer to your fix and patch this gem in the near future. Thank you :)
(If you create pull request, I welcome that!)

**Comment by murakmii** [comment]
I earned result same as version 1.3 at version 1.0.

#### PUT to "/" on Unit 1.0

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost
```

```
{
	"success": "Reconfiguration done."
}
```

#### PUT to "/config" on Unit 1.0

```
curl -v -X PUT -d @./config.json --unix-socket path/to/control.unit.sock localhost
```

```
{
	"success": "Reconfiguration done."
}
```

**Comment by Tab10id** [comment]
> OK, Unit that below version 1.3 supports both request path "/" and "/config".
Therefore, I think your fix still keep backward compatibility.

Haha, we did not expect that=) Anyway, it's a nice gem, thank you.
